# This is an example configuration file that might need modifications
# to properly run in your environment
#
# API KEYS
##########
# Some services require you to obtain an API key and provide it here in
# the configuration:
#
#     * OpenExchangeRates (has a free subscription)
#     * Currencylayer (has a a free subscription)
#     * Quandl (has a a free subscription)
#     * BitcoinAverage (has a a free subscription)
#     * Fixer (has a free subscription)
#     * AlphaVantage (has a free subscription)
#     * WorldCoinIndex (has a free subscription)
#     
# The corresponding variables can be defined in the `exchanges` key.


# If true, a new price feed needs manual confirmation
confirm: True

# The producer name(s)
producer: $PRODUCER

# Exchange settings (Here, you may need to add API keys)
exchanges:

    ####################################
    # Fiat Exchange Rates
    ####################################
    fixer:
        klass: Fixer
        api_key: 
        free_subscription: True
        quotes:
            - EUR
            - USD
            - CNY
            - TRY
            - SGD
            - HKD
            - NZD
            - MXN
            - CAD
            - CHF
            - AUD
            - GBP
            - JPY
            - KRW
            - RUB
            - SEK
        bases:
            - USD
            - EUR
            - CNY
            - JPY
            - HKD
        aliases:
            RUB: RUBLE
    openexchangerates:
        klass: OpenExchangeRates
        api_key: 
        free_subscription: True
        quotes:
            - ARS
            - EUR
            - USD
            - CNY
            - TRY
            - SGD
            - HKD
            - NZD
            - MXN
            - CAD
            - CHF
            - AUD
            - GBP
            - JPY
            - KRW
            - SEK
            - RUB
        bases:
            # Only USD with free subscription
            - USD
    currencylayer:
        klass: CurrencyLayer
        api_key: 
        free_subscription: True
        quotes:
            - ARS
            - TRY
            - SGD
            - HKD
            - NZD
            - CNY
            - MXN
            - CAD
            - CHF
            - AUD
            - GBP
            - JPY
            - EUR
            - USD
            - KRW
            - RUB
            - SEK
        bases:
            # Only USD with free subscription
            - USD
        aliases:
            RUB: RUBLE

    ####################################
    # Commodities
    ####################################
    quandl:
        klass: Quandl 
        api_key:
        datasets:
            "GOLD:USD": 
                - LBMA/GOLD
            "SILVER:USD":
                - LBMA/SILVER

    ####################################
    # Bitcoin Exchange Rates
    ####################################
    bitstamp:
        klass: Bitstamp
        quotes:
            - BTC
        bases:
            - USD
            - EUR
    btcavg:
        klass: BitcoinAverage
        secret_key:
        public_key:
        quotes:
            - BTC
        bases:
            - USD
            - EUR
            - CNY
    okcoin:
        klass: Okcoin
        quotes:
            - BTC
        bases:
            - USD
    huobi:
        klass: Huobi 
        enable: False
        quotes:
            - BTC
        bases:
            - CNY
    ####################################
    # Bitcoin Exchange Rates
    ####################################
    poloniex:
        klass: Poloniex
        quotes:
            - BTS
        bases:
            - BTC
    bittrex:
        klass: Bittrex
        enable: False
        quotes:
            - BTS
        bases:
            - BTC
    zb:
        klass: Zb
        quotes:
            - BTS
        bases:
            - BTC
    bitshares:
        klass: Graphene
        quotes:
            - USD
            - CNY
        bases:
            - BTS
    coinmarketcap:
        klass: Coinmarketcap
        quotes:
            - BTC
            - BTS
        bases:
            - BTC
            - USD
    aex:
        klass: Aex
        quotes:
            - BTS
        bases:
            - BTC
    lbank:
        klass: Lbank
        quotes:
            - BTS
        bases:
            - BTC

        
# default settings
default:
    # max age of a feed
    maxage: 43200

    # minimum percentage that forces a publish
    min_change: 0.5

    # warn if price change goes above this percentage
    warn_change: 1.5

    # skip publishing a feed if price goes above this percentage
    skip_change: 3

    # skip publishing a feed if producer is not an active witness.
    skip_inactive_witness: True

    # how to derive a single price from several sources
    # Choose from: "median", "mean", or "weighted" (by volume)
    metric: weighted

    # Select sources for this particular asset. Each source
    # has its own fetch() method and collects several markets
    # any market of an exchanges is considered but only the
    # current asset's price is derived
    #
    # Choose from: - "*": all,
    #              - loaded exchanges (see below)
    sources:
        - fixer
        - openexchangerates
        - currencylayer
        - btcavg
        - quandl
        - bitstamp
        - okcoin
        - poloniex
        - zb
        - coinmarketcap
        - aex
        - bitshares
        - lbank

    # Core exchange factor for paying transaction fees in
    # non-BTS assets. Premium of 5%
    core_exchange_factor: 1.05

    # maintenance collateral ratio (percentage)
    maintenance_collateral_ratio: 175.0

    # Maximum short squeeze ratio
    maximum_short_squeeze_ratio: 110.0

    # If set to True, prices are also derived via 3
    # markets instead of just two:
    # E.g.: GOLD:USD -> USD:BTC -> BTC:BTS = GOLD:BTS
    derive_across_3markets: False


# Enabled assets that are derived if no asset is provided via command
# line
assets:
    BTC:
    USD:
    CNY:
        core_exchange_factor: 1.2
    TRY:
    RUBLE:
    EUR:
    AUD:
    JPY:
    CHF:
    MXN:
    GBP:
    CAD:
    ARS:
    HKD:
    SEK:
    SGD:
    NZD:
    KRW:
    RUB:
    GOLD:
    SILVER:

# Intermediate assets are useful for 2 and 3 market price derivation
# E.g.: USD:BTC -> BTC:BTS = USD:BTS
#       GOLD:USD -> USD:BTC -> BTC:BTS = GOLD:BTS
intermediate_assets:
    - CNY
    - USD
    - BTC
